### PR TITLE
Refactored Dribbble::Base behavior and added Comments and a PaginatedList

### PR DESCRIPTION
**Pull request by catharinejm**
Jeremy,

Michael Parenteau and I are working on a project using swish and I've added a few things to suit our needs. They're pretty general and I thought they might be of use in the main branch. Essentially I refactored Dribbble::Base to behave like an OpenStruct, though I didn't use OpenStruct because it won't overwrite existing methods in its ruby 1.8.x implementation. This way the methods on the swish objects will always exactly match the dribble API response. I also added Dribbble::Comment, a Dribbble::Shot#comments method, and a PaginatedList object which retains the pagination metadata (pages, total, etc.).

There are tests for the new functionality, though admittedly they could probably be better. If you have any feedback, or if there's something I could change which would make my update more palatable for you I'd love to hear it.

Thanks!
Jon Distad

### CODE REVIEW

**Comment by jeremyw** [comment]
Hi Jon,

Sorry for the late reply. I like these changes a lot! I actually planned to do something very similar to the PaginatedList you implemented. I also think the OpenStruct-style is probably better than the explicit accessors.

I'll do a more thorough review and pull your changes later today, but it looks great. Thanks!

By the way, is the project you're using swish in public yet?

**Comment by catharinejm** [comment]
No worries! Again, if there's anything you'd want done differently, I'm happy to make the changes and resubmit.

The project we're using swish on just went public 30 minutes ago! http://hooppps.com.

I'm also working on putting a redis cache between swish and the API both for speed and to prevent accidental API abuse. It's still very basic and possibly not useful, but it's in the redis branch of the michaelparenteau fork.

**Comment by jeremyw** [comment]
Sorry for the delay. So I _finally_ got around to taking a look at this! I pulled everything but the redis bit -- I'm not super familiar with redis myself yet (it's on my list of things to learn this year) and didn't want to add an "advanced" dependency that might deter people from fiddling with the API or dropping this into a project that doesn't already depend on redis.

I think it's a great idea though, especially since no one wants to cause excessive load on a bootstrapped startup like Dribbble. Do you think it would be worthwhile to extract the redis stuff into a separate gem that somehow plugs into Swish as a caching strategy? I imagine a simple interface that others could plug into, e.g. memcached for a simpler but less persistent cache.

Thanks for your work on this. Hooppps is awesome!

**Comment by catharinejm** [comment]
The separate gem may make sense. The redis stuff needs a lot of work though. I'm not sure that it achieves anything other than making it less likely you'll hit the 60 requests per minute limit on the API. Regardless, I'm in agreement that it doesn't belong in swish. I just put it there for my own convenience. I didn't realize github would include it in my pull request at the time.

I will let you know if/when anything happens along those lines.

**Comment by jeremyw** [comment]
Thanks. In the meantime, I'll close this pull request.

**Pull request closed without merging**
